### ISSUE TITLE
SavedMode by note not working

### ISSUE THREAD

**Issue by affvalente** [standardnotes/markdown-basic#46]
hi - 

I have found an issue with savedMode. It’s not working for me - when I change the mode in one note, the editor stays in the new mode when I go to another note, even if that new one has a different savedMode

https://github.com/standardnotes/markdown-basic/blob/f7fa66820e2d84278145ea1c9971bcbabface3f3/app/components/Home.js#L117

Thanks

**Comment by JaspalSuri** [comment]
Hi @affvalente, I'll take note of this and forward it over to the dev team for further review. 🙂

**Comment by affvalente** [comment]
Thanks - having looked through the metadata in a few test notes, it doesn't seem the editor is saving or reading the metadata actually

**Comment by johnny243** [comment]
Hi @affvalente, thanks for reporting this! A fix for this bug should be available soon :)

**Comment by affvalente** [comment]
Great!
